services:
  - type: web
    name: archive-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: archive-db
          property: connectionString

databases:
  - name: archive-db
    plan: free

